exec sp_setreptable Nickname ,true
exec sp_setreptable OpeninglineAdminLog ,true
exec sp_setreptable Openingline ,true
exec sp_setreptable ProfilePicture ,true
exec sp_setreptable ProfilePictureAdminLog ,true
exec sp_setreptable EntryAdminLog ,true
exec sp_setreptable Note ,true
exec sp_setreptable NoteId ,true
exec sp_setreptable CrmToLavalife ,true
exec sp_setreptable Profile ,true
exec sp_setreptable UserPartnerInfo ,true
exec sp_setreptable RemovedProfile ,true
exec sp_setreptable PrimeInactiveLog ,true
exec sp_setreptable UserInfo ,true
exec sp_setreptable Msg ,true
exec sp_setreptable Entry ,true
exec sp_setreptable MsgId ,true
exec sp_setreptable EntryDescription ,true
exec sp_setreptable Media ,true
exec sp_setreptable MediaId ,true
exec sp_setreptable EntryId ,true
exec sp_setreptable CookieId ,true
exec sp_setreptable Contest ,true
exec sp_setreptable Cookie ,true
exec sp_setreptable Signup ,true
exec sp_setreptable Session ,true
exec sp_setreptable SessionHistory ,true
exec sp_setreptable Blocklist ,true
exec sp_setreptable MailId ,true
exec sp_setreptable ForumCategory ,true
exec sp_setreptable MailStatus ,true
exec sp_setreptable ForumTopicId ,true
exec sp_setreptable Mail ,true
exec sp_setreptable ForumTopic ,true
exec sp_setreptable ForumCommentId ,true
--exec sp_setreptable MailBody ,true
exec sp_setreptable NicknameLock ,true
exec sp_setreptable ForumComment ,true
exec sp_setreptable OpeninglineLock ,true
exec sp_setreptable ForumDescription ,true
exec sp_setreptable ProfilePictureLock ,true
exec sp_setreptable ForumTopicVote ,true
exec sp_setreptable EntryLock ,true
exec sp_setreptable SpamVote ,true
exec sp_setreptable ForumCommentVote ,true
exec sp_setreptable NicknameAdminLog ,true
go
